import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/NavBar";
import { AuthProvider } from "@/context/AuthContext";
import ReduxProvider from "../context/ReduxProvider";
import ForceZoom from "@/components/layout/ForceZoom";
import { Footer } from "../components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dragon Slayer (text RPG)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#CBA35C] overflow-hidden ${geistSans.variable} ${geistMono.variable} antialiased text-xl`}
      >
        <ForceZoom />
        <AuthProvider>
          <ReduxProvider>
            <Navbar />
            <div className="pt-[64px]">{children}</div>
            <Footer />
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
